// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrxuhrtvvdgajihjqsfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeHVocnR2dmRnYWppaGpxc2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDE2OTMsImV4cCI6MjA1OTU3NzY5M30.WU5dx2lvFMkfVnlaXSuT8GXwsrGDvIjiWfqriuahD9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);